 DROP TABLE BCode;
 CREATE TABLE BCode (
    bNumber NUMBER(3) PRIMARY KEY,
    bCodename VARCHAR(100));
SELECT * FROM BCode;
INSERT INTO BCode VALUES (000,'총류');
INSERT INTO BCode VALUES (001, '지식, 학문 일반');
INSERT INTO BCode VALUES (003, '이론체계 및 시스템');
INSERT INTO BCode VALUES (004, '컴퓨터과학');
INSERT INTO BCode VALUES (005, '프로그래밍, 프로그램, 데이터');
INSERT INTO BCode VALUES (007, '연구 일반 및 방법론');
INSERT INTO BCode VALUES (010, '도서학, 서지학');
INSERT INTO BCode VALUES (011, '저작');
INSERT INTO BCode VALUES (012, '사본, 판본, 제본');
INSERT INTO BCode VALUES (013, '출판 및 판매');
INSERT INTO BCode VALUES (014, '개인서지 및 목록');
INSERT INTO BCode VALUES (015, '국가별서지 및 목록');
INSERT INTO BCode VALUES (016, '주제별서지 및 목록');
INSERT INTO BCode VALUES (017, '특수서지 및 목록');
INSERT INTO BCode VALUES (018, '일반서지 및 목록');
INSERT INTO BCode VALUES (019, '장서목록');
INSERT INTO BCode VALUES (020, '문헌정보학');
INSERT INTO BCode VALUES (021, '도서관 행정 및 재정');
INSERT INTO BCode VALUES (022, '도서관 건물 및 설비');
INSERT INTO BCode VALUES (023, '도서관 경영, 관리');
INSERT INTO BCode VALUES (024, '수서, 정리 및 보존');
INSERT INTO BCode VALUES (025, '도서관 봉사 및 활동');
INSERT INTO BCode VALUES (026, '일반 도서관');
INSERT INTO BCode VALUES (027, '학교 및 대학도서관');
INSERT INTO BCode VALUES (028, '기록관리');
INSERT INTO BCode VALUES (029, '독서 및 정보매체의 이용');
INSERT INTO BCode VALUES (030, '백과사전');
INSERT INTO BCode VALUES (031, '한국어');
INSERT INTO BCode VALUES (032, '중국어');
INSERT INTO BCode VALUES (033, '일본어');
INSERT INTO BCode VALUES (034, '영어');
INSERT INTO BCode VALUES (035, '독일어');
INSERT INTO BCode VALUES (036, '프랑스어');
INSERT INTO BCode VALUES (037, '스페인어');
INSERT INTO BCode VALUES (038, '이탈리아어');
INSERT INTO BCode VALUES (039, '기타 제언어');
INSERT INTO BCode VALUES (040, '강연집, 수필집, 연설문집');
INSERT INTO BCode VALUES (041, '한국어');
INSERT INTO BCode VALUES (042, '중국어');
INSERT INTO BCode VALUES (043, '일본어');
INSERT INTO BCode VALUES (044, '영어');
INSERT INTO BCode VALUES (045, '독일어');
INSERT INTO BCode VALUES (046, '프랑스어');
INSERT INTO BCode VALUES (047, '스페인어');
INSERT INTO BCode VALUES (048, '이탈리아어');
INSERT INTO BCode VALUES (049, '기타 제언어');
INSERT INTO BCode VALUES (050, '일반 연속간행물');
INSERT INTO BCode VALUES (051, '한국어');
INSERT INTO BCode VALUES (052, '중국어');
INSERT INTO BCode VALUES (053, '일본어');
INSERT INTO BCode VALUES (054, '영어');
INSERT INTO BCode VALUES (055, '독일어');
INSERT INTO BCode VALUES (056, '프랑스어');
INSERT INTO BCode VALUES (057, '스페인어');
INSERT INTO BCode VALUES (058, '기타 제언어');
INSERT INTO BCode VALUES (059, '연감');
INSERT INTO BCode VALUES (060, '일반 학회, 단체, 협회, 기관');
INSERT INTO BCode VALUES (061, '아시아 일반 학회, 단체 등');
INSERT INTO BCode VALUES (062, '유럽 일반 학회, 단체 등');
INSERT INTO BCode VALUES (063, '아프리카 일반 학회, 단체 등');
INSERT INTO BCode VALUES (064, '북아메리카 일반 학회, 단체 등');
INSERT INTO BCode VALUES (065, '남아메리카 일반 학회, 단체 등');
INSERT INTO BCode VALUES (066, '오세아니아 일반 학회, 단체 등');
INSERT INTO BCode VALUES (067, '양극지방 일반 학회, 단체 등');
INSERT INTO BCode VALUES (068, '해양');
INSERT INTO BCode VALUES (069, '박물관학');
INSERT INTO BCode VALUES (070, '신문, 저널리즘');
INSERT INTO BCode VALUES (071, '아시아 신문, 저널리즘 등');
INSERT INTO BCode VALUES (072, '유럽 신문, 저널리즘 등');
INSERT INTO BCode VALUES (073, '아프리카 신문, 저널리즘 등');
INSERT INTO BCode VALUES (074, '북아메리카 신문, 저널리즘 등');
INSERT INTO BCode VALUES (075, '남아메리카 신문, 저널리즘 등');
INSERT INTO BCode VALUES (076, '오세아니아 신문, 저널리즘 등');
INSERT INTO BCode VALUES (077, '양극지방 신문, 저널리즘 등');
INSERT INTO BCode VALUES (078, '특정주제의 신문');
INSERT INTO BCode VALUES (080, '일반전집, 총서');
INSERT INTO BCode VALUES (081, '개인의 일반 전집');
INSERT INTO BCode VALUES (082, '2인 이상의 일반 전집, 총서');
INSERT INTO BCode VALUES (090, '향토자료');
INSERT INTO BCode VALUES (100, '철학');
INSERT INTO BCode VALUES (101, '이론 및 철학의 효용');
INSERT INTO BCode VALUES (102, '잡저');
INSERT INTO BCode VALUES (103, '사전, 사전, 어사전');
INSERT INTO BCode VALUES (104, '강연집, 수필집');
INSERT INTO BCode VALUES (105, '연속간행물');
INSERT INTO BCode VALUES (106, '학회, 단체, 협회, 기관, 회의');
INSERT INTO BCode VALUES (107, '지도법, 연구법 및 교육, 교육자료');
INSERT INTO BCode VALUES (108, '총서, 전집, 선집');
INSERT INTO BCode VALUES (109, '철학사');
INSERT INTO BCode VALUES (110, '형이상학');
INSERT INTO BCode VALUES (111, '방법론');
INSERT INTO BCode VALUES (112, '존재론');
INSERT INTO BCode VALUES (113, '우주론 및 자연철학');
INSERT INTO BCode VALUES (114, '공간');
INSERT INTO BCode VALUES (115, '시간');
INSERT INTO BCode VALUES (116, '운동과 변화');
INSERT INTO BCode VALUES (117, '구조');
INSERT INTO BCode VALUES (118, '힘과 에너지');
INSERT INTO BCode VALUES (119, '물량과 질량');
INSERT INTO BCode VALUES (120, '인식론, 인과론, 인간학');
INSERT INTO BCode VALUES (121, '인식론');
INSERT INTO BCode VALUES (122, '인과론');
INSERT INTO BCode VALUES (123, '자유 및 필연');
INSERT INTO BCode VALUES (124, '목적론');
INSERT INTO BCode VALUES (125, '가치론');
INSERT INTO BCode VALUES (126, '철학적 인간학');
INSERT INTO BCode VALUES (130, '철학의 체계');
INSERT INTO BCode VALUES (131, '관념론 및 연관철학');
INSERT INTO BCode VALUES (132, '비판철학');
INSERT INTO BCode VALUES (133, '합리론');
INSERT INTO BCode VALUES (134, '인문주의');
INSERT INTO BCode VALUES (135, '경험론');
INSERT INTO BCode VALUES (136, '자연주의');
INSERT INTO BCode VALUES (137, '유물론');
INSERT INTO BCode VALUES (138, '과학주의');
INSERT INTO BCode VALUES (139, '기타');
INSERT INTO BCode VALUES (140, '경학');
INSERT INTO BCode VALUES (141, '역류');
INSERT INTO BCode VALUES (142, '서류');
INSERT INTO BCode VALUES (143, '시류');
INSERT INTO BCode VALUES (144, '예류');
INSERT INTO BCode VALUES (145, '악류');
INSERT INTO BCode VALUES (146, '춘추류');
INSERT INTO BCode VALUES (147, '효경');
INSERT INTO BCode VALUES (148, '사서');
INSERT INTO BCode VALUES (150, '동양철학, 사상');
INSERT INTO BCode VALUES (151, '한국철학, 사상');
INSERT INTO BCode VALUES (152, '중국철학, 사상');
INSERT INTO BCode VALUES (153, '일본철학, 사상');
INSERT INTO BCode VALUES (154, '동남아시아 제국 철학, 사상');
INSERT INTO BCode VALUES (155, '인도철학, 사상');
INSERT INTO BCode VALUES (156, '중앙아시아 제국 철학, 사상');
INSERT INTO BCode VALUES (157, '시베리아 철학, 사상');
INSERT INTO BCode VALUES (158, '서남아시아 제국 철학, 사상');
INSERT INTO BCode VALUES (159, '아라비아반도 철학, 사상');
INSERT INTO BCode VALUES (160, '서양철학');
INSERT INTO BCode VALUES (162, '미국철학');
INSERT INTO BCode VALUES (163, '북구철학');
INSERT INTO BCode VALUES (164, '영국철학');
INSERT INTO BCode VALUES (165, '독일, 오스트리아철학');
INSERT INTO BCode VALUES (166, '프랑스, 네덜란드철학');
INSERT INTO BCode VALUES (167, '스페인철학');
INSERT INTO BCode VALUES (168, '이탈리아철학');
INSERT INTO BCode VALUES (169, '러시아철학');
INSERT INTO BCode VALUES (170, '논리학');
INSERT INTO BCode VALUES (171, '연역법');
INSERT INTO BCode VALUES (172, '귀납법');
INSERT INTO BCode VALUES (173, '번증법적 논리학');
INSERT INTO BCode VALUES (174, '기소, 수리논리학');
INSERT INTO BCode VALUES (175, '오류');
INSERT INTO BCode VALUES (176, '삼단논법');
INSERT INTO BCode VALUES (177, '가설, 가정');
INSERT INTO BCode VALUES (178, '유추');
INSERT INTO BCode VALUES (179, '논증, 설득');
INSERT INTO BCode VALUES (180, '심리학');
INSERT INTO BCode VALUES (181, '심리학각론');
INSERT INTO BCode VALUES (182, '차이심리학');
INSERT INTO BCode VALUES (183, '발달심리학');
INSERT INTO BCode VALUES (184, '이상심리학');
INSERT INTO BCode VALUES (185, '생리심리학');
INSERT INTO BCode VALUES (186, '임상심리학');
INSERT INTO BCode VALUES (187, '심령연구 및 비학, 초심리학');
INSERT INTO BCode VALUES (188, '상법, 운명판단');
INSERT INTO BCode VALUES (189, '응용심리학 일반');
INSERT INTO BCode VALUES (190, '윤리학, 도덕철학');
INSERT INTO BCode VALUES (191, '일반윤리학 각론');
INSERT INTO BCode VALUES (192, '가정윤리');
INSERT INTO BCode VALUES (193, '국가 및 정치윤리');
INSERT INTO BCode VALUES (194, '사회윤리');
INSERT INTO BCode VALUES (195, '직업윤리 일반');
INSERT INTO BCode VALUES (196, '오락 및 경기윤리');
INSERT INTO BCode VALUES (197, '성윤리 및 생식윤리');
INSERT INTO BCode VALUES (198, '소비윤리');
INSERT INTO BCode VALUES (199, '도덕훈, 교훈');
INSERT INTO BCode VALUES (200, '종교');
INSERT INTO BCode VALUES (201, '종교철학 및 종교사상');
INSERT INTO BCode VALUES (202, '잡저');
INSERT INTO BCode VALUES (203, '사전(辭典), 사전(事典)');
INSERT INTO BCode VALUES (204, '자연종교, 자연신학');
INSERT INTO BCode VALUES (205, '연속간행물');
INSERT INTO BCode VALUES (206, '학회, 단체, 협회, 기관, 회의');
INSERT INTO BCode VALUES (207, '지도법, 연구법 및 교육, 교육자료');
INSERT INTO BCode VALUES (208, '총서, 전집, 선집');
INSERT INTO BCode VALUES (209, '종교사');
INSERT INTO BCode VALUES (210, '비교종교');
INSERT INTO BCode VALUES (211, '교리');
INSERT INTO BCode VALUES (212, '종교창시자(교주) 및 제자');
INSERT INTO BCode VALUES (213, '경전, 성전');
INSERT INTO BCode VALUES (214, '종교신앙, 신앙록, 신앙활동, 수도생활');
INSERT INTO BCode VALUES (215, '선교, 포교, 전도, 교육활동');
INSERT INTO BCode VALUES (216, '종단, 교단(교단론)');
INSERT INTO BCode VALUES (217, '예배형식, 의식, 의례');
INSERT INTO BCode VALUES (218, '종파, 교파');
INSERT INTO BCode VALUES (219, '신화, 신화학');
INSERT INTO BCode VALUES (220, '불교');
INSERT INTO BCode VALUES (221, '불교교리');
INSERT INTO BCode VALUES (222, '부처, 보살, 불제자');
INSERT INTO BCode VALUES (223, '경전(불전, 불경, 대장경)');
INSERT INTO BCode VALUES (224, '종교신앙, 신앙록, 신앙생활');
INSERT INTO BCode VALUES (225, '포교, 교육, 교화활동');
INSERT INTO BCode VALUES (226, '사원론');
INSERT INTO BCode VALUES (227, '법회, 의식, 행사(의궤)');
INSERT INTO BCode VALUES (228, '종파');
INSERT INTO BCode VALUES (229, '라마교');
INSERT INTO BCode VALUES (230, '기독교');
INSERT INTO BCode VALUES (231, '기독교신학, 교의학(조직신학)');
INSERT INTO BCode VALUES (232, '예수 그리스도, 사도');
INSERT INTO BCode VALUES (233, '성서(성경)');
INSERT INTO BCode VALUES (234, '종교신앙, 신앙록, 신앙생활');
INSERT INTO BCode VALUES (235, '전도, 교육, 교화 활동, 목회학');
INSERT INTO BCode VALUES (236, '교회론');
INSERT INTO BCode VALUES (237, '예배, 의식, 성례');
INSERT INTO BCode VALUES (238, '교파');
INSERT INTO BCode VALUES (239, '유대교(유태교)');
INSERT INTO BCode VALUES (240, '도교');
INSERT INTO BCode VALUES (241, '교의, 신선사상');
INSERT INTO BCode VALUES (242, '교주, 개조(장도릉)');
INSERT INTO BCode VALUES (243, '도장');
INSERT INTO BCode VALUES (244, '신앙록, 신앙생활');
INSERT INTO BCode VALUES (245, '포교, 전도, 교육, 교육 활동');
INSERT INTO BCode VALUES (246, '사원론(도관)');
INSERT INTO BCode VALUES (247, '행사, 법술');
INSERT INTO BCode VALUES (248, '교파');
INSERT INTO BCode VALUES (250, '천도교');
INSERT INTO BCode VALUES (251, '교리');
INSERT INTO BCode VALUES (252, '종교창시자(교주) 및 제자');
INSERT INTO BCode VALUES (253, '경전, 성전');
INSERT INTO BCode VALUES (254, '종교신앙, 신앙록, 신앙활동, 수도생활');
INSERT INTO BCode VALUES (255, '선교, 포교, 전도, 교육활동');
INSERT INTO BCode VALUES (256, '종단, 교단(교단론)');
INSERT INTO BCode VALUES (257, '예배형식, 의식, 의례');
INSERT INTO BCode VALUES (258, '동학교분파');
INSERT INTO BCode VALUES (259, '단군교, 대종교');
INSERT INTO BCode VALUES (270, '힌두교, 브라만교');
INSERT INTO BCode VALUES (271, '교리');
INSERT INTO BCode VALUES (272, '종교창시자(교주) 및 제자');
INSERT INTO BCode VALUES (273, '경전, 성전');
INSERT INTO BCode VALUES (274, '종교신앙, 신앙록, 신앙활동, 수도생활');
INSERT INTO BCode VALUES (275, '선교, 포교, 전도, 교육활동');
INSERT INTO BCode VALUES (276, '종단, 교단(교단론)');
INSERT INTO BCode VALUES (277, '예배형식, 의식, 의례');
INSERT INTO BCode VALUES (278, '종파, 교파');
INSERT INTO BCode VALUES (279, '자이나교');
INSERT INTO BCode VALUES (280, '이슬람교(회교)');
INSERT INTO BCode VALUES (281, '교리');
INSERT INTO BCode VALUES (282, '종교창시자(교주) 및 제자');
INSERT INTO BCode VALUES (283, '경전, 성전');
INSERT INTO BCode VALUES (284, '종교신앙, 신앙록, 신앙활동, 수도생활');
INSERT INTO BCode VALUES (285, '선교, 포교, 전도, 교육활동');
INSERT INTO BCode VALUES (286, '종단, 교단(교단론)');
INSERT INTO BCode VALUES (287, '예배형식, 의식, 의례');
INSERT INTO BCode VALUES (288, '종파, 교파');
INSERT INTO BCode VALUES (289, '조로아스터교(요교, 배화교)');
INSERT INTO BCode VALUES (290, '기타 제종교');
INSERT INTO BCode VALUES (291, '아시아');
INSERT INTO BCode VALUES (292, '유럽');
INSERT INTO BCode VALUES (293, '아프리카');
INSERT INTO BCode VALUES (294, '북아메리카');
INSERT INTO BCode VALUES (295, '남아메리카');
INSERT INTO BCode VALUES (296, '오세아니아, 양극지방');
INSERT INTO BCode VALUES (299, '기타 다른 기원의 종교');
INSERT INTO BCode VALUES (300, '사회과학');
INSERT INTO BCode VALUES (301, '사회사상');
INSERT INTO BCode VALUES (302, '잡저');
INSERT INTO BCode VALUES (303, '사전(辭典), 사전(事典)');
INSERT INTO BCode VALUES (304, '강연집, 수필집, 연설문집');
INSERT INTO BCode VALUES (305, '연속간행물');
INSERT INTO BCode VALUES (306, '학회, 단체, 협회, 기관, 회의');
INSERT INTO BCode VALUES (307, '연구법, 연구방법 및 교육, 교육자료');
INSERT INTO BCode VALUES (308, '총서, 전집, 선집');
INSERT INTO BCode VALUES (309, '사회 문화 사정');
INSERT INTO BCode VALUES (310, '통계자료');
INSERT INTO BCode VALUES (311, '아시아');
INSERT INTO BCode VALUES (312, '유럽');
INSERT INTO BCode VALUES (313, '아프리카');
INSERT INTO BCode VALUES (314, '북아메리카');
INSERT INTO BCode VALUES (315, '남아메리카');
INSERT INTO BCode VALUES (316, '오세아니아, 양극지방');
INSERT INTO BCode VALUES (317, '일반지역');
INSERT INTO BCode VALUES (319, '인구통계');
INSERT INTO BCode VALUES (320, '경제학');
INSERT INTO BCode VALUES (321, '경제각론');
INSERT INTO BCode VALUES (322, '경제정책');
INSERT INTO BCode VALUES (323, '산업경제, 일반');
INSERT INTO BCode VALUES (324, '기업경제');
INSERT INTO BCode VALUES (325, '경영');
INSERT INTO BCode VALUES (326, '상업, 교통, 통신');
INSERT INTO BCode VALUES (327, '금융');
INSERT INTO BCode VALUES (328, '보험');
INSERT INTO BCode VALUES (329, '재정');
INSERT INTO BCode VALUES (330, '사회학, 사회문제');
INSERT INTO BCode VALUES (331, '사회학');
INSERT INTO BCode VALUES (332, '사회 조직 및 제도');
INSERT INTO BCode VALUES (334, '사회문제');
INSERT INTO BCode VALUES (335, '생활문제');
INSERT INTO BCode VALUES (337, '여성문제');
INSERT INTO BCode VALUES (338, '사회복지');
INSERT INTO BCode VALUES (339, '사회단체');
INSERT INTO BCode VALUES (340, '정치학');
INSERT INTO BCode VALUES (341, '국가형태');
INSERT INTO BCode VALUES (342, '국가와 개인 및 집단');
INSERT INTO BCode VALUES (344, '선거');
INSERT INTO BCode VALUES (345, '입법');
INSERT INTO BCode VALUES (346, '정당');
INSERT INTO BCode VALUES (349, '외교, 국제관계');
INSERT INTO BCode VALUES (350, '행정학');
INSERT INTO BCode VALUES (351, '아시아');
INSERT INTO BCode VALUES (352, '유럽');
INSERT INTO BCode VALUES (353, '아프리카');
INSERT INTO BCode VALUES (354, '북아메리카');
INSERT INTO BCode VALUES (355, '남아메리카');
INSERT INTO BCode VALUES (356, '오세아니아, 양극지방');
INSERT INTO BCode VALUES (357, '일반지역');
INSERT INTO BCode VALUES (359, '지방자치 및 지방행정');
INSERT INTO BCode VALUES (360, '법률, 법학');
INSERT INTO BCode VALUES (361, '국제법');
INSERT INTO BCode VALUES (362, '헌법');
INSERT INTO BCode VALUES (363, '행정법');
INSERT INTO BCode VALUES (364, '형법');
INSERT INTO BCode VALUES (365, '민법');
INSERT INTO BCode VALUES (366, '상법');
INSERT INTO BCode VALUES (367, '사법제도 및 소송법');
INSERT INTO BCode VALUES (368, '기타 제법');
INSERT INTO BCode VALUES (369, '각국 법 및 예규');
INSERT INTO BCode VALUES (370, '교육학');
INSERT INTO BCode VALUES (371, '교육정책 및 행정');
INSERT INTO BCode VALUES (372, '학교행정 및 경영, 보건 및 교육지도');
INSERT INTO BCode VALUES (373, '학습지도, 교육방법');
INSERT INTO BCode VALUES (374, '교육과정');
INSERT INTO BCode VALUES (375, '유아 및 초등교육');
INSERT INTO BCode VALUES (376, '중등교육');
INSERT INTO BCode VALUES (377, '대학, 전문, 고등교육');
INSERT INTO BCode VALUES (378, '평생교육');
INSERT INTO BCode VALUES (379, '특수교육');
INSERT INTO BCode VALUES (380, '풍속, 예절, 민속학');
INSERT INTO BCode VALUES (381, '의식주의 풍습');
INSERT INTO BCode VALUES (382, '연령별, 성별, 신분별, 사회계층의 풍습');
INSERT INTO BCode VALUES (383, '사회생활의 풍습');
INSERT INTO BCode VALUES (384, '관혼상제');
INSERT INTO BCode VALUES (385, '예절');
INSERT INTO BCode VALUES (386, '축제, 세시풍속');
INSERT INTO BCode VALUES (388, '민속학');
INSERT INTO BCode VALUES (389, '문화인류학');
INSERT INTO BCode VALUES (390, '국방, 군사학');
INSERT INTO BCode VALUES (391, '군사행정');
INSERT INTO BCode VALUES (392, '전략, 전술');
INSERT INTO BCode VALUES (393, '군사교육 및 훈련');
INSERT INTO BCode VALUES (394, '군사시설 및 장비');
INSERT INTO BCode VALUES (395, '군특수기술근무');
INSERT INTO BCode VALUES (396, '육군');
INSERT INTO BCode VALUES (397, '해군');
INSERT INTO BCode VALUES (398, '공군');
INSERT INTO BCode VALUES (399, '고대병법');
INSERT INTO BCode VALUES (400, '자연과학');
INSERT INTO BCode VALUES (410, '수학');
INSERT INTO BCode VALUES (420, '물리학');
INSERT INTO BCode VALUES (430, '화학');
INSERT INTO BCode VALUES (440, '천문학');
INSERT INTO BCode VALUES (450, '지구과학');
INSERT INTO BCode VALUES (460, '광물학');
INSERT INTO BCode VALUES (470, '생명과학');
INSERT INTO BCode VALUES (480, '식물학');
INSERT INTO BCode VALUES (490, '동물학');
INSERT INTO BCode VALUES (500, '기술과학');
INSERT INTO BCode VALUES (510, '의학');
INSERT INTO BCode VALUES (520, '농업, 농학');
INSERT INTO BCode VALUES (530, '공학, 공업 일반, 토목공학, 환경공학');
INSERT INTO BCode VALUES (540, '건축공학');
INSERT INTO BCode VALUES (550, '기계공학');
INSERT INTO BCode VALUES (560, '전기공학, 전자공학');
INSERT INTO BCode VALUES (570, '화학공학');
INSERT INTO BCode VALUES (580, '제조업');
INSERT INTO BCode VALUES (590, '생활과학');
INSERT INTO BCode VALUES (600, '예술');
INSERT INTO BCode VALUES (620, '조각 및 조형미술');
INSERT INTO BCode VALUES (630, '공예, 장식미술');
INSERT INTO BCode VALUES (640, '서예');
INSERT INTO BCode VALUES (650, '회화, 도화');
INSERT INTO BCode VALUES (660, '사진 예술');
INSERT INTO BCode VALUES (670, '음악');
INSERT INTO BCode VALUES (680, '공연예술 및 매체예술');
INSERT INTO BCode VALUES (690, '오락, 스포츠');
INSERT INTO BCode VALUES (700, '언어');
INSERT INTO BCode VALUES (701, '언어학');
INSERT INTO BCode VALUES (702, '잡저');
INSERT INTO BCode VALUES (703, '사전');
INSERT INTO BCode VALUES (704, '강연집, 수필집');
INSERT INTO BCode VALUES (705, '연속간행물');
INSERT INTO BCode VALUES (706, '학회, 단체, 기관, 회의');
INSERT INTO BCode VALUES (707, '지도법, 연구법 및 교육, 교육자료');
INSERT INTO BCode VALUES (708, '전집, 총서');
INSERT INTO BCode VALUES (709, '언어사 및 언어정책, 언어행정');
INSERT INTO BCode VALUES (710, '한국어');
INSERT INTO BCode VALUES (711, '음운, 음성, 문자');
INSERT INTO BCode VALUES (712, '어원, 어의');
INSERT INTO BCode VALUES (713, '사전');
INSERT INTO BCode VALUES (714, '어휘');
INSERT INTO BCode VALUES (715, '문법');
INSERT INTO BCode VALUES (716, '작문');
INSERT INTO BCode VALUES (717, '독본, 해석, 회화');
INSERT INTO BCode VALUES (718, '방언(사투리)');
INSERT INTO BCode VALUES (720, '중국어');
INSERT INTO BCode VALUES (721, '음운, 음성, 문자');
INSERT INTO BCode VALUES (722, '어원, 어의');
INSERT INTO BCode VALUES (723, '사전');
INSERT INTO BCode VALUES (724, '어휘');
INSERT INTO BCode VALUES (725, '문법, 어법');
INSERT INTO BCode VALUES (726, '작문');
INSERT INTO BCode VALUES (727, '독본, 해석, 회화');
INSERT INTO BCode VALUES (728, '방언(사투리)');
INSERT INTO BCode VALUES (730, '일본어 및 기타 아시아제어');
INSERT INTO BCode VALUES (731, '음운, 음성, 문자');
INSERT INTO BCode VALUES (732, '어원, 어의');
INSERT INTO BCode VALUES (733, '사전');
INSERT INTO BCode VALUES (734, '어휘');
INSERT INTO BCode VALUES (735, '문법');
INSERT INTO BCode VALUES (736, '작문');
INSERT INTO BCode VALUES (737, '독본, 해석, 회화');
INSERT INTO BCode VALUES (738, '방언(사투리)');
INSERT INTO BCode VALUES (739, '기타 아시아 제어');
INSERT INTO BCode VALUES (740, '영어');
INSERT INTO BCode VALUES (741, '음운, 음성, 문자');
INSERT INTO BCode VALUES (742, '어원, 어의');
INSERT INTO BCode VALUES (743, '사전');
INSERT INTO BCode VALUES (744, '어휘');
INSERT INTO BCode VALUES (745, '문법');
INSERT INTO BCode VALUES (746, '작문');
INSERT INTO BCode VALUES (747, '독본, 해석, 회화');
INSERT INTO BCode VALUES (748, '방언(사투리)');
INSERT INTO BCode VALUES (749, '앵글로색슨어');
INSERT INTO BCode VALUES (750, '독일어');
INSERT INTO BCode VALUES (751, '음운, 음성, 문자');
INSERT INTO BCode VALUES (752, '어원, 어의');
INSERT INTO BCode VALUES (753, '사전');
INSERT INTO BCode VALUES (754, '어휘');
INSERT INTO BCode VALUES (756, '문법');
INSERT INTO BCode VALUES (756, '작문');
INSERT INTO BCode VALUES (757, '독본, 해석, 회화');
INSERT INTO BCode VALUES (758, '방언(사투리)');
INSERT INTO BCode VALUES (759, '기타 게르만어');
INSERT INTO BCode VALUES (760, '프랑스어');
INSERT INTO BCode VALUES (761, '음운, 음성, 문자');
INSERT INTO BCode VALUES (762, '어원, 어의');
INSERT INTO BCode VALUES (763, '사전');
INSERT INTO BCode VALUES (764, '어휘');
INSERT INTO BCode VALUES (765, '문법');
INSERT INTO BCode VALUES (766, '작문');
INSERT INTO BCode VALUES (767, '독본, 해석, 회화');
INSERT INTO BCode VALUES (768, '방언(사투리)');
INSERT INTO BCode VALUES (769, '프로방스어');
INSERT INTO BCode VALUES (770, '스페인어');
INSERT INTO BCode VALUES (771, '음운, 음성, 문자');
INSERT INTO BCode VALUES (772, '어원, 어의');
INSERT INTO BCode VALUES (773, '사전');
INSERT INTO BCode VALUES (774, '어휘');
INSERT INTO BCode VALUES (775, '문법');
INSERT INTO BCode VALUES (776, '작문');
INSERT INTO BCode VALUES (777, '독본, 해석, 회화');
INSERT INTO BCode VALUES (778, '방언(사투리)');
INSERT INTO BCode VALUES (779, '포르투갈어');
INSERT INTO BCode VALUES (780, '이탈리아어');
INSERT INTO BCode VALUES (781, '음운, 음성, 문자');
INSERT INTO BCode VALUES (782, '어원, 어의');
INSERT INTO BCode VALUES (783, '사전');
INSERT INTO BCode VALUES (784, '어휘');
INSERT INTO BCode VALUES (785, '문법');
INSERT INTO BCode VALUES (786, '작문');
INSERT INTO BCode VALUES (787, '독본, 해석, 회화');
INSERT INTO BCode VALUES (788, '방언(사투리)');
INSERT INTO BCode VALUES (789, '루마니아어');
INSERT INTO BCode VALUES (790, '기타 제어');
INSERT INTO BCode VALUES (792, '인도유럽어');
INSERT INTO BCode VALUES (793, '아프리카 제어');
INSERT INTO BCode VALUES (794, '북아메리카 인디안어');
INSERT INTO BCode VALUES (795, '남아메리카 인디안어');
INSERT INTO BCode VALUES (796, '오스트로네시아어족');
INSERT INTO BCode VALUES (797, '셈어족');
INSERT INTO BCode VALUES (798, '함어족');
INSERT INTO BCode VALUES (799, '국제어(인공어) 및 기타 언어');
INSERT INTO BCode VALUES (800, '문학');
INSERT INTO BCode VALUES (801, '문학이론');
INSERT INTO BCode VALUES (802, '문장작법, 수사학');
INSERT INTO BCode VALUES (803, '사전(辭典), 사전(事典)');
INSERT INTO BCode VALUES (804, '강연집, 수필');
INSERT INTO BCode VALUES (805, '연속간행물');
INSERT INTO BCode VALUES (806, '학회, 단체, 기관, 회의');
INSERT INTO BCode VALUES (807, '지도법 및 연구법, 교육, 교육자료');
INSERT INTO BCode VALUES (808, '전집, 총서');
INSERT INTO BCode VALUES (809, '문학사, 평론');
INSERT INTO BCode VALUES (810, '한국문학');
INSERT INTO BCode VALUES (811, '시');
INSERT INTO BCode VALUES (812, '희곡');
INSERT INTO BCode VALUES (813, '소설');
INSERT INTO BCode VALUES (814, '수필');
INSERT INTO BCode VALUES (815, '연설, 웅변');
INSERT INTO BCode VALUES (816, '일기, 서간, 기행');
INSERT INTO BCode VALUES (817, '풍자');
INSERT INTO BCode VALUES (818, '르포르타주 및 기타');
INSERT INTO BCode VALUES (820, '중국문학');
INSERT INTO BCode VALUES (821, '시');
INSERT INTO BCode VALUES (822, '희곡');
INSERT INTO BCode VALUES (823, '소설');
INSERT INTO BCode VALUES (824, '수필');
INSERT INTO BCode VALUES (825, '연설, 웅변');
INSERT INTO BCode VALUES (826, '일기, 서간, 기행');
INSERT INTO BCode VALUES (827, '풍자');
INSERT INTO BCode VALUES (828, '르포르타주 및 기타');
INSERT INTO BCode VALUES (830, '일본문학 및 기타 아시아문학');
INSERT INTO BCode VALUES (831, '시');
INSERT INTO BCode VALUES (832, '희곡');
INSERT INTO BCode VALUES (833, '소설');
INSERT INTO BCode VALUES (834, '수필');
INSERT INTO BCode VALUES (835, '연설, 웅변');
INSERT INTO BCode VALUES (836, '일기, 서간, 기행');
INSERT INTO BCode VALUES (837, '풍자');
INSERT INTO BCode VALUES (838, '르포르타주 및 기타');
INSERT INTO BCode VALUES (839, '기타 아시아 제문학');
INSERT INTO BCode VALUES (840, '영미문학');
INSERT INTO BCode VALUES (841, '시');
INSERT INTO BCode VALUES (842, '희곡');
INSERT INTO BCode VALUES (843, '소설');
INSERT INTO BCode VALUES (844, '수필');
INSERT INTO BCode VALUES (845, '연설, 웅변');
INSERT INTO BCode VALUES (846, '일기, 서간, 기행');
INSERT INTO BCode VALUES (847, '풍자');
INSERT INTO BCode VALUES (848, '르포르타주 및 기타');
INSERT INTO BCode VALUES (849, '미국문학');
INSERT INTO BCode VALUES (850, '독일문학');
INSERT INTO BCode VALUES (851, '시');
INSERT INTO BCode VALUES (852, '희곡');
INSERT INTO BCode VALUES (853, '소설');
INSERT INTO BCode VALUES (854, '수필');
INSERT INTO BCode VALUES (855, '연설, 웅변');
INSERT INTO BCode VALUES (856, '일기, 서간, 기행');
INSERT INTO BCode VALUES (857, '풍자');
INSERT INTO BCode VALUES (858, '르포르타주 및 기타');
INSERT INTO BCode VALUES (859, '기타 게르만 문학');
INSERT INTO BCode VALUES (860, '프랑스문학');
INSERT INTO BCode VALUES (861, '시');
INSERT INTO BCode VALUES (862, '희곡');
INSERT INTO BCode VALUES (863, '소설');
INSERT INTO BCode VALUES (864, '수필');
INSERT INTO BCode VALUES (865, '연설, 웅변');
INSERT INTO BCode VALUES (866, '일기, 서간, 기행');
INSERT INTO BCode VALUES (867, '풍자');
INSERT INTO BCode VALUES (868, '르포르타주 및 기타');
INSERT INTO BCode VALUES (869, '프로방스문학');
INSERT INTO BCode VALUES (870, '스페인문학 및 포르투갈문학');
INSERT INTO BCode VALUES (871, '시');
INSERT INTO BCode VALUES (872, '희곡');
INSERT INTO BCode VALUES (873, '소설');
INSERT INTO BCode VALUES (874, '수필');
INSERT INTO BCode VALUES (875, '연설, 웅변');
INSERT INTO BCode VALUES (876, '일기, 서간, 기행');
INSERT INTO BCode VALUES (877, '풍자');
INSERT INTO BCode VALUES (878, '르포르타주 및 기타');
INSERT INTO BCode VALUES (879, '포르투갈문학');
INSERT INTO BCode VALUES (880, '이탈리아문학');
INSERT INTO BCode VALUES (881, '시');
INSERT INTO BCode VALUES (882, '희곡');
INSERT INTO BCode VALUES (883, '소설');
INSERT INTO BCode VALUES (884, '수필');
INSERT INTO BCode VALUES (885, '연설, 웅변');
INSERT INTO BCode VALUES (886, '일기, 서간, 기행');
INSERT INTO BCode VALUES (887, '풍자');
INSERT INTO BCode VALUES (888, '르포르타주 및 기타');
INSERT INTO BCode VALUES (889, '루마니아문학');
INSERT INTO BCode VALUES (890, '기타 제문학');
INSERT INTO BCode VALUES (892, '인도-유럽계문학');
INSERT INTO BCode VALUES (893, '아프리카제문학');
INSERT INTO BCode VALUES (894, '북아메리카 인디언문학');
INSERT INTO BCode VALUES (895, '남아메리카 인디언문학');
INSERT INTO BCode VALUES (896, '오스트로네시아문학');
INSERT INTO BCode VALUES (897, '셈족문학');
INSERT INTO BCode VALUES (898, '함족문학');
INSERT INTO BCode VALUES (899, '기타 문학');
INSERT INTO BCode VALUES (900, '역사');
INSERT INTO BCode VALUES (901, '역사 철학 및 이론');
INSERT INTO BCode VALUES (902, '역사보조학');
INSERT INTO BCode VALUES (903, '사전, 사전');
INSERT INTO BCode VALUES (904, '강연집, 사평');
INSERT INTO BCode VALUES (905, '연속간행물');
INSERT INTO BCode VALUES (906, '학회, 단체, 기관, 회의');
INSERT INTO BCode VALUES (907, '지도법, 연구법 및 교육, 교육자료');
INSERT INTO BCode VALUES (908, '전집, 총서');
INSERT INTO BCode VALUES (909, '세계사, 세계문화사');
INSERT INTO BCode VALUES (910, '아시아');
INSERT INTO BCode VALUES (911, '한국');
INSERT INTO BCode VALUES (912, '중국');
INSERT INTO BCode VALUES (913, '일본');
INSERT INTO BCode VALUES (914, '동남아시아');
INSERT INTO BCode VALUES (915, '인디아와 남부아시아');
INSERT INTO BCode VALUES (916, '중앙아시아');
INSERT INTO BCode VALUES (917, '시베리아');
INSERT INTO BCode VALUES (918, '서남아시아, 중동');
INSERT INTO BCode VALUES (919, '아라비아반도와 인접지역');
INSERT INTO BCode VALUES (920, '유럽');
INSERT INTO BCode VALUES (921, '고대 그리스(희랍고대사)');
INSERT INTO BCode VALUES (922, '고대 로마');
INSERT INTO BCode VALUES (923, '스칸디나비아');
INSERT INTO BCode VALUES (924, '영국, 아일랜드');
INSERT INTO BCode VALUES (925, '독일과 중앙유럽');
INSERT INTO BCode VALUES (926, '프랑스와 인접국가');
INSERT INTO BCode VALUES (927, '스페인과 인접국가');
INSERT INTO BCode VALUES (928, '이탈리아와 인접국가');
INSERT INTO BCode VALUES (929, '러시아와 동부유럽');
INSERT INTO BCode VALUES (930, '아프리카');
INSERT INTO BCode VALUES (931, '북아프리카');
INSERT INTO BCode VALUES (934, '서아프리카');
INSERT INTO BCode VALUES (936, '중앙아프리카');
INSERT INTO BCode VALUES (937, '동아프리카');
INSERT INTO BCode VALUES (938, '남아프리카');
INSERT INTO BCode VALUES (939, '남인도양제도');
INSERT INTO BCode VALUES (940, '북아메리카');
INSERT INTO BCode VALUES (941, '캐나다');
INSERT INTO BCode VALUES (942, '미국(미합중국)');
INSERT INTO BCode VALUES (943, '멕시코');
INSERT INTO BCode VALUES (944, '중앙아메리카(중미제국)');
INSERT INTO BCode VALUES (945, '과테말라, 벨리즈, 엘살바도르');
INSERT INTO BCode VALUES (946, '온두라스');
INSERT INTO BCode VALUES (947, '니카라과');
INSERT INTO BCode VALUES (948, '코스타리카, 파나마');
INSERT INTO BCode VALUES (949, '서인도제도');
INSERT INTO BCode VALUES (950, '남아메리카');
INSERT INTO BCode VALUES (951, '콜롬비아');
INSERT INTO BCode VALUES (952, '베네수엘라와 기아나 지역');
INSERT INTO BCode VALUES (953, '브라질');
INSERT INTO BCode VALUES (954, '에콰도르');
INSERT INTO BCode VALUES (955, '페루');
INSERT INTO BCode VALUES (956, '볼리비아');
INSERT INTO BCode VALUES (957, '파라과이, 우루과이');
INSERT INTO BCode VALUES (958, '아르헨티나');
INSERT INTO BCode VALUES (959, '칠레');
INSERT INTO BCode VALUES (960, '오세아니아, 양극지방');
INSERT INTO BCode VALUES (962, '오스트레일리아(호주)');
INSERT INTO BCode VALUES (963, '뉴질랜드');
INSERT INTO BCode VALUES (964, '파푸아뉴기니');
INSERT INTO BCode VALUES (965, '멜라네시아');
INSERT INTO BCode VALUES (966, '미크로네시아와 인접 국가');
INSERT INTO BCode VALUES (967, '폴리네시아와 하와이');
INSERT INTO BCode VALUES (968, '대서양제도');
INSERT INTO BCode VALUES (969, '양극지방');
INSERT INTO BCode VALUES (970, '미분류');
INSERT INTO BCode VALUES (980, '지리');
INSERT INTO BCode VALUES (981, '아시아지리');
INSERT INTO BCode VALUES (982, '유럽지리');
INSERT INTO BCode VALUES (983, '아프리카지리');
INSERT INTO BCode VALUES (984, '북아메리카지리');
INSERT INTO BCode VALUES (985, '남아메리카지리');
INSERT INTO BCode VALUES (986, '오세아니아지리와 양극 지리');
INSERT INTO BCode VALUES (987, '지역 구분 일반지리');
INSERT INTO BCode VALUES (988, '해양');
INSERT INTO BCode VALUES (989, '지도 및 지도책');
INSERT INTO BCode VALUES (990, '전기');
INSERT INTO BCode VALUES (991, '아시아전기');
INSERT INTO BCode VALUES (992, '유럽전기');
INSERT INTO BCode VALUES (993, '아프리카전기');
INSERT INTO BCode VALUES (994, '북아메리카전기');
INSERT INTO BCode VALUES (995, '남아메리카전기');
INSERT INTO BCode VALUES (996, '오세아니아와 양극 전기');
INSERT INTO BCode VALUES (998, '주제별 전기');
INSERT INTO BCode VALUES (999, '계보, 족보');