DROP TABLE LIBRARYBORROW;
DROP SEQUENCE LIBRARYBORROW_SEQ;
CREATE SEQUENCE LIBRARYBORROW_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

CREATE TABLE LIBRARYBORROW (
    lbNum NUMBER(6) PRIMARY KEY,
    lCallnum VARCHAR2(100) REFERENCES LIBRARY(LCallnum),
    mId VARCHAR2(100) REFERENCES Member(mId),
    lbDate DATE DEFAULT SYSDATE,
    lbREdate DATE DEFAULT SYSDATE+14,
    lbREALre DATE);
    
SELECT BOOK.*, (SELECT COUNT(*) FROM LIBRARYBORROW WHERE BOOK.LCALLNUM=LIBRARYBORROW.LCALLNUM AND lbREALre IS NULL) FROM LIBRARY BOOK ORDER BY LCALLNUM;
-- 대출 처리
UPDATE LIBRARY SET LBORROW = 'N' WHERE LCALLNUM=5;
INSERT INTO LIBRARYBORROW (LBNUM, LCALLNUM, MID)
    VALUES (LIBRARYBORROW_SEQ.NEXTVAL, '5', 'aaa');
SELECT * FROM LIBRARYBORROW;
select * from library where ldel='N';

SELECT * FROM LIBRARYBORROW WHERE lCallnum=7 AND LBREALRE IS NULL;
UPDATE LIBRARY SET LBORROW = 'Y' WHERE lCallnum=5;
-- 빌려져있는책 불러오기
SELECT * FROM LIBRARYBORROW WHERE LCALLNUM='5' AND LBREALRE IS NULL; 
-- 내가 빌린책
SELECT L.*,mId FROM LIBRARY L, LIBRARYBORROW B WHERE L.LCALLNUM = B.LCALLNUM AND B.mId='aaa' AND LBREALRE IS NULL;
SELECT COUNT(*) FROM LIBRARY L, LIBRARYBORROW B WHERE L.LCALLNUM = B.LCALLNUM AND B.mId='aaa' AND LBREALRE IS NULL;
-- 대출되어있는 책 보기ADMIN
SELECT * FROM LIBRARYBORROW WHERE LBREALRE IS NULL;
-- 반납 예정일이 지난 책 보기ADMIN
SELECT * FROM LIBRARYBORROW WHERE LBREALRE IS NULL AND lbREdate<SYSDATE;
-- 반납처리할때 반납일 갱신ADMIN
UPDATE LIBRARYBORROW SET lbREALre = SYSDATE WHERE lCallnum = 1;
-- 현황보기
SELECT * FROM 
        (SELECT ROWNUM RN, A.* FROM 
            (SELECT  LBNUM, B.LCALLNUM, LTITLE, MID, LBDATE, LBREDATE, LBREALRE FROM LIBRARYBORROW B, LIBRARY L WHERE B.lCallNum=L.lCallNum ORDER BY lbNum DESC) A) 
            WHERE RN BETWEEN 1 AND 5;
            
select * from library where lcallnum=5;
select * from library;
SELECT * FROM LIBRARYBORROW WHERE lCallnum=5 AND LBREALRE IS NULL;
commit;